logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  rabbitmq:
    host: porpoise.rmq.cloudamqp.com
    username: myfgoyvw
    virtual-host: myfgoyvw
    password: QCh4T6au141-Mx_VXI04f_L6zPCLtp8i
  main:
    banner-mode: OFF
